export type HTTP_METHODS = "GET" | "PATCH" | "PUT" | "POST" | "DELETE" | "OPTIONS";

type AUTH_ROUTES = "LOGIN" | "LOGOUT" | "REGISTER" | "RECOVER_ACCOUNT" | "VERIFY" | "RESEND_CODE" | "RESET_PASSWORD";
type NOTE_ROUTES = "GET_ALL_NOTES" | "CREATE_NOTE" | "UPDATE_NOTE" | "DELETE_NOTE";
type USER_ROUTES = "GET_LOGGED_IN_USER" | "UPDATE_USER" | "DELETE_USER";
type UPLOAD_ROUTES = "UPLOAD_IMAGES" | "UPLOAD_AUDIO" | "DELETE_FILES";

type API_ROUTES = AUTH_ROUTES | NOTE_ROUTES | USER_ROUTES | UPLOAD_ROUTES;

export type Endpoint = {
    URL: string;
    METHOD: HTTP_METHODS;
}

export type Endpoints = {
    [key in API_ROUTES]: Endpoint
}